# Generated by Django 4.0.3 on 2023-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('created', 'created'), ('completed', 'completed')], default='created', max_length=100),
        ),
    ]
