# Generated by Django 4.0.3 on 2023-06-06 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vip_status',
            field=models.BooleanField(default=False),
        ),
    ]
